import { FaStar, FaStarHalf } from "react-icons/fa";

export let products = [
  {
    id: 1,
    src: "/image7.png",
    title: "T-shirt With Tape Detail",
    price: 120,
    originalPrice: 120,
    discount: 0,
    rating: 4.5,
    reviews: 5,
    star: 4,
    HalfStar: 1,
    qty: 1,
    color: ["red", "blue", "black"],
    size: ["Small", "Medium", "Large", "X-Large"],
    image1: "/image33.png",
    image2: "/image34.png",
    image3: "/image35.png",
  },
  {
    id: 2,
    src: "/image8.png",
    title: "Skinny Fit Jeans",
    price: 220,
    originalPrice: 260,
    discount: 20,
    rating: 3.5,
    reviews: 5,
    star: 3,
    HalfStar: 1,
    qty: 1,
    color: ["green", "blue", "black"],
    size: ["Small", "Medium", "Large", "X-Large"],
    image1: "/image33.png",
    image2: "/image34.png",
    image3: "/image35.png",
  },
  {
    id: 3,
    src: "/image9.png",
    title: "Checkered Shirt",
    price: 180,
    originalPrice: 180,
    discount: 0,
    rating: 4.5,
    reviews: 5,
    star: 4,
    HalfStar: 1,
    qty: 1,
    color: ["red", "blue", "black"],
    size: ["Small", "Medium", "Large", "X-Large"],
    image1: "/image33.png",
    image2: "/image34.png",
    image3: "/image35.png",
  },
  {
    id: 4,
    src: "/image10.png",
    title: "Sleeve Stripped T-Shirt",
    price: 160,
    originalPrice: 130,
    discount: 30,
    rating: 4.5,
    reviews: 5,
    star: 4,
    HalfStar: 1,
    qty: 1,
    color: ["red", "blue", "black"],
    size: ["Small", "Medium", "Large", "X-Large"],
    image1: "/image33.png",
    image2: "/image34.png",
    image3: "/image35.png",
  },
  {
    id: 5,
    src: "/image11.png",
    title: "Casual Shirt",
    price: 150,
    originalPrice: 150,
    discount: 0,
    rating: 4.0,
    reviews: 10,
    star: 4,
    HalfStar: 0,
    qty: 1,
    color: ["white", "blue"],
    size: ["Small", "Medium", "Large"],
    image1: "/image33.png",
    image2: "/image34.png",
    image3: "/image35.png",
  },
  {
    id: 6,
    src: "/image12.png",
    title: "Formal Pants",
    price: 200,
    originalPrice: 200,
    discount: 0,
    rating: 3.5,
    reviews: 8,
    star: 3,
    HalfStar: 1,
    qty: 1,
    color: ["black", "gray"],
    size: ["Medium", "Large", "X-Large"],
    image1: "/image33.png",
    image2: "/image34.png",
    image3: "/image35.png",
  },
  {
    id: 7,
    src: "/image13.png",
    title: "Denim Jacket",
    price: 350,
    originalPrice: 250,
    discount: 0,
    rating: 4.5,
    reviews: 15,
    star: 4,
    HalfStar: 1,
    qty: 1,
    color: ["blue", "black"],
    size: ["Small", "Medium", "Large", "X-Large"],
    image1: "/image33.png",
    image2: "/image34.png",
    image3: "/image35.png",
  },
  {
    id: 8,
    src: "/image14.png",
    title: "Leather Shoes",
    price: 300,
    originalPrice: 200,
    discount: 0,
    rating: 5.0,
    reviews: 20,
    star: 5,
    HalfStar: 0,
    qty: 1,
    color: ["brown", "black"],
    size: ["medium", "large"],
    image1: "/image33.png",
    image2: "/image34.png",
    image3: "/image35.png",
  },
];